### ISSUE TITLE
STKPush Query Request error

### ISSUE THREAD

**Issue by bedann** [safaricom/LNMOnlineAndroidSample#13]
When i try to check the status of a Lipa Na M-pesa payment request, i keep getting this error
{
  "requestId": "ws_CO_20022018230142206",
  "errorCode": "500.001.1001",
  "errorMessage": "The transaction is being processed"
}

**Comment by kisese** [comment]
@bedann That is the standard response from the Mpesa Express Query status API. It means the transaction went through and is being processed
