### ISSUE TITLE
No response received at callback url endpoint

### ISSUE THREAD

**Issue by Aleqi** [safaricom/LNMOnlineAndroidSample#16]
Hi, everything is working perfectly well with the api on the android side but the callback endpoint at the server is not receiving any response. Please help

**Comment by nellycheboi12** [comment]
@Aleqi any luck with this.  I having the same problem

**Comment by kisese** [comment]
@Aleqi @nellycheboi12 You need to define your own callback URL inorder to receive the callbacks. Use this tutorial on how you can use firebase and PHP for that https://www.androidhive.info/2012/10/android-push-notifications-using-google-cloud-messaging-gcm

**Comment by Aleqi** [comment]
I have already defined my own callback and previously it was working
perfectly. But since Thursday 29th March, 2018 last week there is no
response being received at my callback endpoint from mpesa server.

**Comment by Aleqi** [comment]
@nellycheboi12  No luck yet

**Comment by Aleqi** [comment]
Finally it's working. I can get response at the callback endpoint.  It was
a bug on the api developers side.

**Comment by weddingjuma** [comment]
@Aleqi I have the same issue, which kind a bug was it, cant get responses on my callback url. Like the c2b urls, are we suppose to register this STK callback url?

**Comment by ngangavic** [comment]
I came to notice that there are some servers that have a problem with this and after several times of retrying Mpesa drop the response

**Comment by weddingjuma** [comment]
I think thats the reason for my case, I will try changing server

**Comment by kalyangadgil** [comment]
hello @Aleqi 

what kind of bug you were getting at api side ? I am implementing Lipa Na Mpesa STK push and I am not getting response at my callback url after transaction .

please help

**Comment by itsKirk** [comment]
it's strange. I simply cannot get any response from Safaricom through the callbackurl despite all systems working fine previously. What kind of a bug is this @Aleqi? Hey @nellycheboi did you resolve yours?

**Comment by em-manuel** [comment]
Any luck @itsKirk ?

**Comment by itsKirk** [comment]
yeah @em-manuel it turned out to be a bug and it was only on sandbox environment. After two days I got a response from Daraja API guys and confirmed the same but all is well now.

**Comment by angwandi** [comment]
This issue is still there. Sometimes it works, most of the time the endpoint doesn't get the response from Safaricom. Frustrating really.

**Comment by em-manuel** [comment]
@angwandi, 
I have resolved to going straight to production environment to avoid the massive time wastage on the sandbox environment.

**Comment by ngangavic** [comment]
> @angwandi, I have resolved to going straight to production environment to avoid the massive time wastage on the sandbox environment.

This is the best possible solution

**Comment by angwandi** [comment]
@ngangavic @em-manuel I think I will do the same then. Thank you.

 But what's the point of offering a sandbox test account that doesn't work?

**Comment by mwongeraE** [comment]
Still a problem

**Comment by samuelmaina** [comment]
Well someone can get the result of the test transaction by querying mpesa with the CheckoutRequestID (this is returned in the body of initial sdk ).One can make a post request to [https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query](https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query).
I found how to query by login->select APIs->click on query button in the M-Pesa Express card.
Hope this helps those in test env but I would suggest one moves to production to avoid the many hustle of dealing with CheckoutRequestIDs
