### ISSUE TITLE
django api error

### ISSUE THREAD

**Issue by kimrop19** [safaricom/LNMOnlineAndroidSample#20]
I have never used lipa na mpesa in my django projects before but I am now. I have been trying to figure out what to do but I dont even get anything. I think this is because their is less documentation that shows developers how to query the database to the **mpesapy**  if their is any way please can I get help
I followed the documentation https://pythonhosted.org/django-mpesapy/getting_started.html but got an error when I browsed ->**http://127.0.0.1:8000/mpesa/c2b_bill**
the error was that the page never loads and the error message it gave was ->
 **"GET /mpesa/c2b_bill HTTP/1.1" 405 0
Method Not Allowed (GET): /mpesa/c2b_bill not showing any page**
maybe  I can get what to do and can help me solve this

**Comment by kisese** [comment]
@kimrop19 for python related issues please seek assistance on the python repo
