### ISSUE TITLE
Runtime errors

### ISSUE THREAD

**Issue by Patrick-Elvis** [safaricom/LNMOnlineAndroidSample#25]
error: self-reference in initializer
This is the error I get when I try running the app
![no](https://user-images.githubusercontent.com/29231486/44535278-4be6f300-a702-11e8-90af-d89076318571.PNG)

**Comment by kelvinmarshall** [comment]
I'm having this issue too.I'm yet to figure it out

**Comment by kelvinmarshall** [comment]
The issue is in the following lines of code in the build. gradle app module
`buildTypes.each {
        it.buildConfigField 'String', 'CONSUMER_KEY', 'CONSUMER_KEY'
        it.buildConfigField 'String', 'CONSUMER_SECRET', 'CONSUMER_SECRET'
    }`

Change the parameter values according to the values given  in the safaricom developers site

**Comment by kelvinmarshall** [comment]
Cool

**Comment by Patrick-Elvis** [comment]
Thank You
