### ISSUE TITLE
The STK push payment popup not happening

### ISSUE THREAD

**Issue by livingstonenjaria** [safaricom/LNMOnlineAndroidSample#29]
I have been trying for a while but the STK push payment pop up is not occuring leading to a SMSC ACK timeout error

**Comment by expertest123** [comment]
I am facing same issue. if you have resolved kindly help me to resolve.
thanks.

**Comment by livingstonenjaria** [comment]
Spoke to safaricom and they gave me a lazy response saying that the problem is the sim card not the api and that i need to renew or upgrade my sim card, which presents a problem because most users will have old simcards so the API wont have reach and leaves your users hanging.

**Comment by kisese** [comment]
Not a code related issue
