### ISSUE TITLE
Bad request in business shortcode 

### ISSUE THREAD

**Issue by SnowJunior** [safaricom/LNMOnlineAndroidSample#46]
{
                    "requestId":"324-23234973-1",
                    "errorCode": "400.002.02",
                    "errorMessage": "Bad Request - Invalid BusinessShortCode"
                }

**Comment by ngangavic** [comment]
@George-Onyango is this response for sandbox mode or production?

**Comment by SnowJunior** [comment]
sandbox

**Comment by HorraceMuendo** [comment]
@George-Onyango did you manage to fix this ?

**Comment by SnowJunior** [comment]
Yeah I was able to fix the issue. Made an article too in case someone else faces the same issue. https://snowsnippets.hashnode.dev/ruby-and-mpesa-api-how-to-integrate-daraja-api-using-ruby
