### ISSUE TITLE
Use the encryptInitiatorPassword method from docs

### ISSUE THREAD

**Issue by Doggodoggo** [safaricom/LNMOnlineAndroidSample#6]
The docs has a method for encrypting the security credentials; It would be helpful if the app incorporates it for example purposes(unless there were issues).

**Comment by kisese** [comment]
Hi @Doggodoggo since the LNMOnline API does not include **_securitycredential_** param, its not included here, however your suggestion for more samples/examples is noted, we will keep working on and availing more examples

**Comment by Doggodoggo** [comment]
Cool, thanks.
