### ISSUE TITLE
App doesn't call the callback 

### ISSUE THREAD

**Issue by Ikiugu** [safaricom/LNMOnlineAndroidSample#7]
I have done everything as described in the Readme file and the code is still now working. Could you please provide the second part of the code (the php code that is used in conjunction with the android code).
I think it would me of much help if one could just clone the repo, change the config.java file and see the code working. That way going through the code would be understandable.

**Comment by kisese** [comment]
Hi @Ikiugu you need to setup a server to receive call backs as detailed in this tutorial https://www.androidhive.info/2012/10/android-push-notifications-using-google-cloud-messaging-gcm-php-and-mysql the phones code is available there

**Comment by Ikiugu** [comment]
Thanks. I'll go through it.
And wouldn't it be better to wait for the person who opened the issue to at least respond before closing it?
